# This is intended as the simplest way to get a complete ArchivesSpace system up and running on a single instance using Docker.
# See also: https://docs.archivesspace.org/administration/docker/

services:
  archivesspace:
    image: archivesspace/archivesspace:${ARCHIVESSPACE_DOCKER_TAG}
    container_name: archivesspace
    env_file:
      - .env
    depends_on:
      - as_solr
    volumes:
      - app-data:/archivesspace/data
      - ./mounted/archivesspace/config:/archivesspace/config
      - ./mounted/archivesspace/plugins:/archivesspace/plugins
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net

      # highest priority, a deep subpath
      - traefik.http.routers.as_api.entrypoints=websecure
      - traefik.http.routers.as_api.rule=Host(`archivesspace-dev.uncw.edu`) && PathPrefix(`/staff/api`)
      - traefik.http.routers.as_api.tls=true
      - traefik.http.routers.as_api.priority=200
      - traefik.http.routers.as_api.service=as_api
      - traefik.http.services.as_api.loadbalancer.server.port=8089

      # med priority, a subpath
      - traefik.http.routers.as_staff.entrypoints=websecure
      - traefik.http.routers.as_staff.rule=Host(`aspace-dev.uncw.edu`)
      - traefik.http.routers.as_staff.tls=true
      - traefik.http.routers.as_staff.priority=100
      - traefik.http.routers.as_staff.service=as_staff
      - traefik.http.services.as_staff.loadbalancer.server.port=8080

      # med priority, a subpath
      - traefik.http.routers.as_oai.entrypoints=websecure
      - traefik.http.routers.as_oai.rule=Host(`archivesspace-dev.uncw.edu`) && PathPrefix(`/oai`)
      - traefik.http.routers.as_oai.tls=true
      - traefik.http.routers.as_oai.priority=100
      - traefik.http.routers.as_oai.service=as_oai
      - traefik.http.services.as_oai.loadbalancer.server.port=8082

      # lowest priority, catch-all default
      - traefik.http.routers.as_public.entrypoints=websecure
      - traefik.http.routers.as_public.rule=Host(`archivesspace-dev.uncw.edu`)
      - traefik.http.routers.as_public.tls=true
      - traefik.http.routers.as_public.priority=1
      - traefik.http.routers.as_public.service=as_public
      - traefik.http.services.as_public.loadbalancer.server.port=8081
    networks:
      - archivesspace_net
      - default
    restart: unless-stopped
    mem_limit: 4g

  as_solr:
    image: archivesspace/solr:${ARCHIVESSPACE_DOCKER_TAG}
    container_name: as_solr
    build: ./solr
    env_file:
      - .env
    volumes:
      - solr-data:/var/solr
    networks:
      - archivesspace_net
    command: solr-create -p 8983 -c archivesspace -d archivesspace
    restart: unless-stopped
    mem_limit: 1536m

volumes:
  app-data:
  solr-data:

networks:
  default:
    name: traefik_net
    external: true
  archivesspace_net:
    internal: true
    driver: bridge