# This is intended as the simplest way to get a complete ArchivesSpace system up and running on a single instance using Docker.
# See also: https://docs.archivesspace.org/administration/docker/

services:
  app:
    image: archivesspace/archivesspace:${ARCHIVESSPACE_DOCKER_TAG}
    container_name: archivesspace
    platform: linux/x86_64
    build: ./archivesspace
    env_file:
      - .env
    depends_on:
      - db
      - solr
    volumes:
      - app-data:/archivesspace/data
      - ./archivesspace/plugins:/archivesspace/plugins
      - ./archivesspace/config:/archivesspace/config
    restart: unless-stopped
    mem_limit: 4g

  solr:
    # image: archivesspace/solr:${ARCHIVESSPACE_DOCKER_TAG}
    image: archivesspace/solr:m1
    container_name: solr
    build: ./solr
    env_file:
      - .env
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command: solr-create -p 8983 -c archivesspace -d archivesspace
    restart: unless-stopped
    mem_limit: 1536m

  proxy:
    image: nginx:1.21
    container_name: proxy
    env_file:
      - .env
    depends_on:
      - app
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./proxy:/etc/nginx/conf.d/
    restart: unless-stopped
    mem_limit: 512m

  db:
    image: mysql:8
    container_name: mysql
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_size=1G  --innodb_buffer_pool_instances=1 --log_bin_trust_function_creators=1
    restart: unless-stopped

  db-backup:
    image: databack/mysql-backup:latest
    container_name: db-backup
    env_file:
      - .env
    environment:
      DB_DUMP_CRON: "0 2 * * *" # UTC
      DB_DUMP_TARGET: /db
      DB_SERVER: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
    command: dump
    volumes:
      - ./backups:/db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  app-data:
  db-data:
  solr-data:
